from flask import Flask, render_template, request, jsonify
from ml_model import predict_image
import os
from flask_cors import CORS

app = Flask(__name__)
CORS(app)
app.config['UPLOAD_FOLDER'] = 'static/uploads'


@app.route('/')
def index():
    return render_template("index.html")


@app.route('/upload', methods=['POST'])
def upload_file():
    if 'file' not in request.files:
        return jsonify({'error': 'No file part'})
    
    file = request.files['file']
    
    if file.filename == '':
        return jsonify({'error': 'No selected file'})

    if file:
        # return jsonify({'error': 'No selected file'})
        # Save the uploaded image to a temporary folder
        file_path = os.path.join(app.config['UPLOAD_FOLDER'], file.filename)
        file.save(file_path)

        # Perform image classification using your pre-trained model
        result = predict_image(file_path)  # Implement this function in ml_model.py

        # You can also remove the uploaded file at this point
        os.remove(file_path)

        class_labels_dict = {'Alpinia Galanga (Rasna)': 'Rasna, hailing from the tropical regions of Southeast Asia, is a cherished herb in Ayurvedic medicine. Its rhizomes possess potent anti-inflammatory properties, making it invaluable for alleviating joint pain and digestive ailments. Rasna has been employed for centuries to enhance overall well-being, particularly in the context of traditional healing practices.',
            'Amaranthus Virdis (Arive-Dantu)': 'Arive-Dantu, predominantly found in the heart of India, is a verdant treasure trove of essential nutrients. Abundant in vitamins and minerals, this leafy green is a cornerstone of local cuisine and traditional medicine. Its consumption supports various facets of health, including improved digestion, enhanced immune function, and the maintenance of optimal nutritional balance.',
            'Artocarpus Heterophyllus (Jackfruit)': 'The majestic Jackfruit tree traces its origins to the lush landscapes of Southeast Asia. Its impressive fruit, known as the "jack of all fruits," is a nutritional powerhouse. Rich in vitamins, minerals, and dietary fiber, Jackfruit contributes to overall well-being by providing essential nutrients. Its culinary versatility has made it a cherished ingredient in a wide array of dishes.',
            'Azadirachta Indica (Neem)': 'Neem, an indigenous inhabitant of the Indian subcontinent, holds a sacred position in traditional healing practices. Revered for its multifaceted medicinal properties, every part of the Neem tree is harnessed for therapeutic purposes. Its leaves, in particular, are celebrated for their potential to enhance skin health, purify the blood, and boost the immune system. Additionally, Neem acts as a natural pesticide and addresses various health concerns, reaffirming its significance in Ayurveda and beyond.',
            'Basella Alba (Basale)': 'Basale, with its origins deeply rooted in the tropical regions of Asia and Africa, is a leafy green with exceptional nutritional value. Abundant in vitamins, minerals, and dietary fiber, Basale is celebrated for its role in promoting overall health. It is known to support cardiovascular health, aid in digestion, and enhance vision, making it a cherished component of local cuisine and traditional remedies.',
            'Brassica Juncea (Indian Mustard)': 'Indian Mustard, cultivated and savored worldwide, is an indispensable staple in culinary traditions. Both its pungent seeds and tender leaves are revered for their distinct flavor and numerous health benefits. Indian Mustard seeds are a rich source of essential nutrients and are commonly used to prepare condiments and oils. The leaves, on the other hand, contribute to the robust flavors of Indian cuisine while providing essential vitamins and minerals. Additionally, Indian Mustard is associated with potential anti-inflammatory and antioxidant properties, further enhancing its significance in traditional medicine.',
            'Carissa Carandas (Karanda)': 'Karanda, a fruit-bearing shrub found in tropical regions, boasts a rich history of traditional medicinal use. Its berries are esteemed for their potential health benefits, including anti-inflammatory and antioxidant properties. Karanda is traditionally utilized to address digestive issues, boost immunity, and promote overall well-being. Its presence in local flora has made it an integral part of indigenous healing practices.',
            'Citrus Limon (Lemon)': 'The illustrious Lemon, cultivated globally, is a quintessential citrus fruit celebrated for its culinary versatility and myriad health benefits. Laden with vitamin C and a host of essential nutrients, Lemons are a potent natural remedy for various ailments. They support immune health, aid in digestion, and promote skin radiance. Additionally, their refreshing flavor and aromatic zest make them a cherished ingredient in diverse culinary creations.',
            'Ficus Auriculata (Roxburgh fig)': 'Roxburgh fig, indigenous to tropical regions, offers both aesthetic beauty and nutritional value. Its sweet and succulent fruit, often consumed fresh or dried, is a source of essential vitamins and minerals. Roxburgh figs are associated with potential health benefits, including improved digestion and enhanced overall well-being. This fig variety adds a touch of natural sweetness to local cuisine while contributing to optimal nutritional balance.',
            'Ficus Religiosa (Peepal Tree)': 'The sacred Peepal Tree, native to the Indian subcontinent, holds a venerable place in Hindu mythology and traditional healing practices. Its heart-shaped leaves are revered for their potential medicinal properties. Peepal leaves are known to have anti-inflammatory, antioxidant, and antimicrobial characteristics, making them a valuable component of herbal remedies. They are traditionally used to address various health concerns, including digestive disorders, respiratory ailments, and skin conditions. Additionally, the Peepal Tree is deeply intertwined with spiritual and cultural significance, symbolizing longevity, wisdom, and enlightenment.',
            'Hibiscus Rosa-sinensis': 'Also known as the Chinese Hibiscus, this vibrant flowering plant is native to East Asia. Its stunning, large blooms come in a variety of colors and are a visual delight. Beyond its ornamental appeal, Hibiscus Rosa-sinensis is utilized in traditional medicine and herbal teas. The plant is known for its potential to support cardiovascular health, lower blood pressure, and provide antioxidant-rich refreshment through the infusion of its petals in beverages like hibiscus tea.',
            'Jasminum (Jasmine)': 'Jasmine, a fragrant flowering plant cultivated worldwide, is known for its aromatic white flowers. Beyond its ornamental value, Jasmine holds cultural significance and is used in perfumery. In traditional medicine, Jasmine is believed to have soothing properties, promoting relaxation and mood enhancement. Its fragrant essence is often utilized in aromatherapy for stress relief.',
            'Mangifera Indica (Mango)': 'Mango, native to South Asia, is a tropical delight cherished for its sweet and juicy fruit. Mangoes are not only a culinary favorite but also a nutritional powerhouse. They provide a rich source of vitamins, particularly vitamin C and A, as well as essential minerals like potassium and fiber. Additionally, mangoes contain antioxidants such as beta-carotene, which contribute to skin health and immune system support. The fruit\'s natural sweetness makes it a versatile ingredient in various dishes, from salsas to smoothies, and its origin in South Asia has made it a symbol of tropical indulgence.',
            'Mentha (Mint)': 'Mint, an aromatic herb with global cultivation, is prized for its refreshing flavor and cooling sensation. This herb finds extensive culinary use in salads, beverages, and desserts. Mint is also a staple in traditional medicine due to its potential health benefits. It is known for its digestive aid properties, relieving indigestion and stomach discomfort. Additionally, menthol, the active compound in mint, provides relief from headaches and nasal congestion. Mint\'s versatility in both culinary and therapeutic applications has made it a beloved herb worldwide.',
            'Moringa Oleifera (Drumstick)': 'Moringa, native to India and widely grown in tropical regions, is celebrated for its nutrient-rich leaves and pods. Often referred to as the "Drumstick Tree" or "Miracle Tree," it is a valuable source of essential vitamins like vitamin C, vitamin A, and vitamin K. Moringa also provides minerals such as calcium, iron, and potassium, along with antioxidants. This nutritional profile makes it a vital addition to diets in regions where it thrives. In traditional medicine, Moringa is utilized to address various health concerns, including digestive issues, inflammation, and fatigue. Its adaptability and rich nutritional content have earned it a reputation as a superfood with the potential to combat malnutrition.',
            'Muntingia Calabura (Jamaica Cherry-Gasagase)': 'Jamaica Cherry, also known as Gasagase, is native to tropical regions and is recognized for its small, vitamin C-rich fruit. The fruit is consumed fresh and is appreciated for its tart-sweet flavor. Jamaica Cherry is known for its potential health benefits, including immune system support due to its vitamin C content. Additionally, it possesses antioxidant properties that help combat oxidative stress. While it may not be as well-known as some other fruits, its significance in tropical diets and traditional remedies is notable.',
            'Murraya Koenigii (Curry)': 'Curry leaves, native to India and other parts of Asia, are an essential component of Indian cuisine and traditional medicine. These aromatic leaves are renowned for their distinctive flavor and aroma. Beyond culinary use, they are believed to have potential health benefits. Curry leaves are considered to aid digestion, reduce cholesterol levels, and possess antioxidant properties. They are also associated with potential antimicrobial and anti-inflammatory effects. As a result, they are a versatile ingredient in cooking and herbal remedies, contributing not only to taste but also to overall well-being.',
            'Nerium Oleander (Oleander)': 'Oleander is an ornamental plant native to the Mediterranean region, characterized by its colorful and toxic flowers. While caution is essential when handling this plant due to its toxicity, it has been used with care in traditional medicine. Oleander extracts are believed to have potential cardiac applications, although their use should be strictly supervised by healthcare professionals. Oleander\'s cultural significance and vibrant blooms have made it a popular ornamental plant, particularly in warm climates.',
            'Nyctanthes Arbor-tristis (Parijata)': 'Parijata, native to India, is known for its fragrant, star-shaped flowers and cultural significance. These flowers are used in traditional medicine for their potential anti-inflammatory and analgesic properties. Parijata is associated with rituals, particularly in Hinduism, and is revered for its beauty and fragrance.',
            'Ocimum Tenuiflorum (Tulsi)': 'Tulsi, also known as Holy Basil, is a sacred herb in India and Asia. It holds a central place in traditional medicine and spiritual practices. Tulsi is celebrated for its holistic healing properties, including the ability to boost the immune system, alleviate respiratory ailments, and promote overall well-being. Its adaptogenic properties help the body adapt to stress, making it a revered herb for maintaining health and vitality.',
            'Piper Betle (Betel)': 'Betel leaves, native to Southeast Asia, have cultural and medicinal significance. They are commonly chewed with areca nut and slaked lime in betel quids. Betel leaves are believed to have mild stimulant and potential digestive properties. Their use is deeply rooted in cultural and social traditions, particularly in South and Southeast Asia.',
            'Plectranthus Amboinicus (Mexican Mint)': 'Mexican Mint, also known as Cuban oregano or Indian borage, is native to East Africa and Asia. It is prized for its aromatic leaves, which have a flavor reminiscent of oregano and thyme. Mexican Mint is used both as a culinary herb and in traditional medicine for its potential to alleviate respiratory issues and aid digestion.',
            'Pongamia Pinnata (Indian Beech)': 'Indian Beech, found in tropical regions, is valued for its seeds and oil. The oil extracted from its seeds, known as karanja oil, has applications in traditional medicine and as a natural insect repellent. Indian Beech is believed to have potential wound-healing properties and is used in skincare products.',
            'Psidium Guajava (Guava)': 'Guava, native to Central America, is renowned for its sweet and tropical fruit. Rich in vitamin C, dietary fiber, and antioxidants, guavas support digestive health and boost immunity. They are consumed fresh, as juices, or in various culinary creations.',
            'Punica Granatum (Pomegranate)': 'Pomegranate, originating from the Middle East, is celebrated for its ruby-red, jewel-like arils. It is a rich source of antioxidants, particularly polyphenols, which promote heart health and combat oxidative stress. Pomegranate juice and seeds are used in both culinary and medicinal applications.',
            'Santalum Album (Sandalwood)': 'Sandalwood, native to India, is prized for its aromatic heartwood. Its essential oil is used in perfumery, skincare, and traditional medicine. Sandalwood oil is believed to have soothing properties for the skin and mind, making it a key ingredient in aromatherapy and cosmetics.',
            'Syzygium Cumini (Jamun)': 'Jamun, native to the Indian subcontinent, produces dark-purple, plum-like fruits. These fruits are rich in antioxidants and are traditionally consumed for their potential to regulate blood sugar levels. Jamun is valued in Ayurvedic medicine for its astringent and anti-diabetic properties.',
            'Syzygium Jambos (Rose Apple)': 'Rose Apple, native to Southeast Asia, produces crisp, bell-shaped fruits with a delicate rose-like aroma. While the fruit is enjoyed fresh, the leaves and bark are used in traditional medicine for potential anti-inflammatory and antipyretic properties.',
            'Tabernaemontana Divaricata (Crape Jasmine)': 'Crape Jasmine, native to India and Southeast Asia, is known for its fragrant white flowers. In traditional medicine, various parts of the plant are used for their potential anti-inflammatory and analgesic properties. Crape Jasmine is also cultivated for its ornamental value.',
            'Trigonella Foenum-graecum (Fenugreek)': 'Fenugreek, native to the Mediterranean region, produces aromatic seeds and leaves. These seeds are a culinary spice and have significance in traditional medicine. Fenugreek seeds are believed to have potential benefits for digestion, blood sugar regulation, and lactation support for nursing mothers.',
        }

        return jsonify({'result': result, 'description': class_labels_dict[result]})


if __name__ == '__main__':
    app.run(host='127.0.0.1', port=3000, debug=True)
